### ISSUE TITLE
imcl install fails as im user

### ISSUE THREAD

**Issue by kennonkwok** [WASdev/ci.chef.iim#9]
This was introduced by 9df7096073f9aec8180eecafc2377a88ea78729a.

When imcl install runs, it attempts to create a registry (~/etc/.ibm/registry/InstallationManager.dat) Previously, imcl install was run as the root user and it was created under /root.  As the im user, it tries to create this under /opt/IBM/InstallationManager and throws the following error:
```
CRIMA1262E ERROR: The installation directory ("/opt/IBM/InstallationManager") must not be the same directory, a parent directory, or sub-directory of the Installation Manager registry directory ("/opt/IBM/InstallationManager/etc/.ibm/registry").
```

Any preference on where the im user's home dir should be?

**Comment by benjamin-confino** [comment]
So I've been informed the reason we have this error is to ensure that when uninstalling IM you don't delete the registry file. Thus I don't want to put it with any of the other directories, to keep the registry safe from an rm -Rf 

That means somewhere underneath either /home or /etc - I chose /home for now as that's the default location for a non-root install of im but I also made it a peramater for anyone who wishes to use /etc

If you think there's a reason to put it elsewhere let me know. Otherwise we can close this issue :)

**Comment by kennonkwok** [comment]
:+1:
